# This example you can switch between 2 LLM's on VS Continue Chat

name: My Config
version: 0.0.1
schema: v1

models:
  - name: gemma4:e4b
    model: gemma4:e4b
    provider: ollama 
    apiBase: http://localhost:11434
    roles:      
      - chat
      - autocomplete
      - edit
      - apply
      - rerank   
  - name: qwen3.5:4b
    model: qwen3.5:4b
    provider: ollama
    apiBase: http://localhost:11434
    roles:      
      - chat
      - autocomplete
      - edit
      - apply
      - rerank
# End of file.
